version: '3.1'
services:
  master:
    image: redis       ## 镜像
    container_name: redis-master
# masterauth  -> 表示和主节点连接时候需要校验的密码
    command: redis-server --requirepass custom_password  --masterauth custom_password 
    ports:
      - "16379:6379"
    networks:
      sentinel-master:
        ipv4_address: 173.17.0.3
    volumes:
      - ./data/redis-maser:/data
  slave1:
    image: redis                ## 镜像
    container_name: redis-slave-1
    ports:
      - "16380:6379"           ## 暴露端口
    command: redis-server --slaveof redis-master 6379 --requirepass custom_password --masterauth custom_password --slave-read-only no
    volumes:
      - ./data/slave1:/data
    depends_on:
      - master
    networks:
      sentinel-master:
        ipv4_address: 173.17.0.2
  slave2:
    image: redis                ## 镜像
    container_name: redis-slave-2
    ports:
      - "16381:6379"           ## 暴露端口
    command: redis-server --slaveof redis-master 6379 --requirepass custom_password --masterauth custom_password --slave-read-only no
    volumes:
      - ./data/slave2:/data
    depends_on:
      - master
    networks:
      sentinel-master:
        ipv4_address: 173.17.0.7
  sentinel1:
    image: redis       ## 镜像
    container_name: redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      sentinel-master:
        ipv4_address: 173.17.0.4
  sentinel2:
    image: redis                ## 镜像
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"           
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      sentinel-master:
        ipv4_address: 173.17.0.5
  sentinel3:
    image: redis                ## 镜像
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"           
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      sentinel-master:
        ipv4_address: 173.17.0.6
networks:
  sentinel-master:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16